# Generated by Django 3.2.1 on 2021-05-05 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangobackend', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Courses',
            new_name='Course',
        ),
    ]
