# Generated by Django 3.2.2 on 2021-05-07 20:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djangobackend', '0002_rename_courses_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_users',
            field=models.ManyToManyField(related_name='course', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='CourseContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_topics', models.CharField(max_length=100)),
                ('course_subtopics', models.TextField(max_length=500)),
                ('course_images', models.ImageField(default='../distributedstudy/frontend/static/images/brain.jpg', upload_to='../distributedstudy/frontend/static/images')),
                ('external_content', models.URLField()),
                ('parent_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangobackend.course')),
            ],
        ),
    ]
