# Generated by Django 3.2.2 on 2021-05-07 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangobackend', '0003_auto_20210507_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='loggedIn',
            field=models.BooleanField(default=False),
        ),
    ]
