# Generated by Django 3.2.2 on 2021-05-08 01:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djangobackend', '0005_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='roomID',
            field=models.CharField(max_length=6, unique=True),
        ),
        migrations.AlterField(
            model_name='coursecontent',
            name='parent_course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangobackend.course', unique=True),
        ),
    ]
