# Generated by Django 3.2.2 on 2021-05-08 16:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djangobackend', '0006_auto_20210507_2022'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursecontent',
            name='course_subtopics',
        ),
        migrations.RemoveField(
            model_name='coursecontent',
            name='external_content',
        ),
        migrations.CreateModel(
            name='CourseSubTopics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(max_length=3)),
                ('external_content', models.URLField()),
                ('course_subtopics', models.ManyToManyField(to='djangobackend.CourseContent')),
                ('post_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
