# Generated by Django 3.2.2 on 2021-05-08 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangobackend', '0008_auto_20210508_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_images',
            field=models.ImageField(default='distributedstudy/images/brain.jpg', upload_to='distributedstudy/images/'),
        ),
    ]
