# Generated by Django 3.2.2 on 2021-05-09 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangobackend', '0009_alter_course_course_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursecontent',
            name='chapters',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coursecontent',
            name='description',
            field=models.TextField(default=1, max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='coursecontent',
            name='course_topics',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
