# Generated by Django 3.2.2 on 2021-05-09 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djangobackend', '0010_auto_20210509_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursecontent',
            name='parent_course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangobackend.course'),
        ),
    ]
