# Generated by Django 3.2.2 on 2021-05-09 21:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djangobackend', '0011_alter_coursecontent_parent_course'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coursesubtopics',
            old_name='content_type',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='coursesubtopics',
            name='course_subtopics',
        ),
        migrations.AddField(
            model_name='coursesubtopics',
            name='parent_content',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='djangobackend.coursecontent'),
            preserve_default=False,
        ),
    ]
